filenames:
  - /hostlogs/traefik/access.log*
labels:
  type: traefik
---
filenames:
  - /hostlogs/auth.log
labels:
  type: syslog
---
filenames:
  - /hostlogs/authelia/*
labels:
  type: authelia
---
filenames:
 - /hostlogs/vaultwarden/*
labels:
  type: Vaultwarden