filenames:
  - /var/log/traefik/access.log*
labels:
  type: traefik
---
filenames:
  - /var/log/auth.log
labels:
  type: syslog
---
filenames:
  - /var/log/authelia/*
labels:
  type: authelia
---
filenames:
 - /var/log/vaultwarden/*
labels:
  type: Vaultwarden