name: ssh-attackers
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip" && lower(Alert.GetScenario() ?? "") contains "ssh"
decisions:
 - type: ban
   duration: 2160h
on_success: break
---
name: cve-scanners
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip" && lower(Alert.GetScenario() ?? "") contains "cve"
decisions:
 - type: ban
   duration: 2160h
on_success: break
---
name: home-countries
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip" && Alert.Source.Cn in ['IN', 'DE']
decisions:
 - type: ban
   duration: 4h
on_success: break
---
name: default-remediation
filters:
 - Alert.Remediation == true && Alert.GetScope() in ["Ip", "Range"]
decisions:
 - type: ban
   duration: 48h
on_success: break
